export const sculptureList = [
    {
      id: 1,
      name: 'Le Penseur',
      artist: 'Auguste Rodin',
      year: 1902,
      description: 'Une sculpture en bronze représentant un homme en profonde méditation.',
    },
    {
      id: 2,
      name: 'David',
      artist: 'Michel-Ange',
      year: 1504,
      description: 'Une célèbre statue en marbre représentant le roi biblique David.',
    },
    {
      id: 3,
      name: 'La Victoire de Samothrace',
      artist: 'Inconnu',
      year: 'Vers 200-190 av. J.-C.',
      description: 'Une sculpture grecque antique représentant la déesse Niké.',
    },
    {
      id: 4,
      name: 'Alexandre le Grand à cheval',
      artist: 'Inconnu',
      year: 'IVe siècle av. J.-C.',
      description: 'Une sculpture en bronze représentant Alexandre le Grand à cheval.',
    },
    {
      id: 5,
      name: 'Buste de Jules César',
      artist: 'Inconnu',
      year: 'Ier siècle av. J.-C.',
      description: 'Un buste en marbre représentant Jules César.',
    },
    {
      id: 6,
      name: 'Napoléon Ier empereur',
      artist: 'Lorenzo Bartolini',
      year: 1809,
      description: 'Une sculpture en bronze représentant Napoléon Ier en empereur romain.',
    },
    // Ajoutez ici les sculptures des rois de France depuis l'ère chrétienne
    {
      id: 7,
      name: 'Statue de Clovis Ier',
      artist: 'Inconnu',
      year: 'Ve siècle',
      description: 'Une sculpture représentant Clovis Ier, premier roi des Francs.',
    },
    {
      id: 8,
      name: 'Statue de Charlemagne',
      artist: 'Inconnu',
      year: 'IXe siècle',
      description: 'Une sculpture représentant Charlemagne, empereur d\'Occident.',
    },
    {
      id: 9,
      name: 'Statue de Louis IX (Saint Louis)',
      artist: 'Inconnu',
      year: 'XIIIe siècle',
      description: 'Une sculpture représentant Louis IX, connu sous le nom de Saint Louis.',
    },
    {
      id: 10,
      name: 'Statue de François Ier',
      artist: 'Inconnu',
      year: 'XVIe siècle',
      description: 'Une sculpture représentant François Ier, roi de France.',
    },
    {
      id: 11,
      name: 'Statue de Louis XIV',
      artist: 'Inconnu',
      year: 'XVIIe siècle',
      description: 'Une sculpture représentant Louis XIV, le Roi Soleil.',
    },
    {
      id: 12,
      name: 'Statue de Louis XVI',
      artist: 'Inconnu',
      year: 'XVIIIe siècle',
      description: 'Une sculpture représentant Louis XVI, roi de France.',
    },
    {
      id: 13,
      name: 'Statue de Charles X',
      artist: 'Inconnu',
      year: 'XIXe siècle',
      description: 'Une sculpture représentant Charles X, roi de France.',
    },
    {
      id: 14,
      name: 'Statue de Louis-Philippe Ier',
      artist: 'Inconnu',
      year: 'XIXe siècle',
      description: 'Une sculpture représentant Louis-Philippe Ier, dernier roi des Français.',
    },
  ];
  